# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ nome: 'Star Wars' }, { nome: 'Lord of the Rings' }])
#   Character.create(nome: 'Luke', movie: movies.first)


Categoria.create( nome: "Alimentos e Bebidas")
Categoria.create( nome: "Arte e Antiguidades")
Categoria.create( nome: "Artigos Religiosos")
Categoria.create( nome: "Assinaturas e Revistas")
Categoria.create( nome: "Automóveis e Veículos")
Categoria.create( nome: "Bebês e Cia")
Categoria.create( nome: "Blu-Ray")
Categoria.create( nome: "Brindes / Materiais Promocionais")
Categoria.create( nome: "Brinquedos e Games")
Categoria.create( nome: "Casa e Decoração")
Categoria.create( nome: "CDs")
Categoria.create( nome: "Colecionáveis")
Categoria.create( nome: "Compras Coletivas")
Categoria.create( nome: "Construção e Ferramentas")
Categoria.create( nome: "Cosméticos e Perfumaria")
Categoria.create( nome: "Cursos e Educação")
Categoria.create( nome: "Discos de Vinil")
Categoria.create( nome: "DVDs")
Categoria.create( nome: "Eletrodomésticos")
Categoria.create( nome: "Eletrônicos")
Categoria.create( nome: "Emissoras de Rádio")
Categoria.create( nome: "Emissoras de Televisão")
Categoria.create( nome: "Empregos")
Categoria.create( nome: "Empresas de Telemarketing")
Categoria.create( nome: "Esporte e Lazer")
Categoria.create( nome: "Fitas K7 Gravadas")
Categoria.create( nome: "Flores, Cestas e Presentes")
Categoria.create( nome: "Fotografia")
Categoria.create( nome: "HD-DVD")
Categoria.create( nome: "Igrejas / Templos / Instituições Religiosas")
Categoria.create( nome: "Indústria, Comércio e Negócios")
Categoria.create( nome: "Infláveis Promocionais")
Categoria.create( nome: "Informática")
Categoria.create( nome: "Ingressos")
Categoria.create( nome: "Instrumentos Musicais")
Categoria.create( nome: "Joalheria")
Categoria.create( nome: "Lazer")
Categoria.create( nome: "LD")
Categoria.create( nome: "Livros")
Categoria.create( nome: "MD")
Categoria.create( nome: "Moda e Acessórios")
Categoria.create( nome: "Motéis")
Categoria.create( nome: "Música Digital")
Categoria.create( nome: "Natal")
Categoria.create( nome: "Negócios e Oportunidades")
Categoria.create( nome: "Outros Serviços")
Categoria.create( nome: "Outros Serviços de Avaliação")
Categoria.create( nome: "Papelaria e Escritório")
Categoria.create( nome: "Páscoa")
Categoria.create( nome: "Pet Shop")
Categoria.create( nome: "Saúde")
Categoria.create( nome: "Serviço Advocaticios")
Categoria.create( nome: "Serviço de Distribuição de Jornais / Revistas")
Categoria.create( nome: "Serviços Administrativos")
Categoria.create( nome: "Serviços Artísticos")
Categoria.create( nome: "Serviços de Abatedouros / Matadouros")
Categoria.create( nome: "Serviços de Aeroportos")
Categoria.create( nome: "Serviços de Agências")
Categoria.create( nome: "Serviços de Aluguel / Locação")
Categoria.create( nome: "Serviços de Armazenagem")
Categoria.create( nome: "Serviços de Assessorias")
Categoria.create( nome: "Serviços de Assistência Técnica / Instalações")
Categoria.create( nome: "Serviços de Associações")
Categoria.create( nome: "Serviços de Bancos de Sangue")
Categoria.create( nome: "Serviços de Bibliotecas")
Categoria.create( nome: "Serviços de Cartórios")
Categoria.create( nome: "Serviços de Casas Lotéricas")
Categoria.create( nome: "Serviços de Confecções")
Categoria.create( nome: "Serviços de Consórcios")
Categoria.create( nome: "Serviços de Consultorias")
Categoria.create( nome: "Serviços de Cooperativas")
Categoria.create( nome: "Serviços de Despachante")
Categoria.create( nome: "Serviços de Engenharia")
Categoria.create( nome: "Serviços de Estacionomentos")
Categoria.create( nome: "Serviços de Estaleiros")
Categoria.create( nome: "Serviços de Exportação / Importação")
Categoria.create( nome: "Serviços de Geólogos")
Categoria.create( nome: "Serviços de joalheiros")
Categoria.create( nome: "Serviços de Leiloeiros")
Categoria.create( nome: "Serviços de limpeza")
Categoria.create( nome: "Serviços de Loja de Conveniência")
Categoria.create( nome: "Serviços de Mão de Obra")
Categoria.create( nome: "Serviços de Órgão Públicos")
Categoria.create( nome: "Serviços de Pesquisas")
Categoria.create( nome: "Serviços de Portos")
Categoria.create( nome: "Serviços de Saúde / Bem Estar")
Categoria.create( nome: "Serviços de Seguradoras")
Categoria.create( nome: "Serviços de Segurança")
Categoria.create( nome: "Serviços de Sinalização")
Categoria.create( nome: "Serviços de Sindicatos / Federações")
Categoria.create( nome: "Serviços de Traduções")
Categoria.create( nome: "Serviços de Transporte")
Categoria.create( nome: "Serviços de Utilidade Pública")
Categoria.create( nome: "Serviços em Agricultura / Pecuária / Piscicultura")
Categoria.create( nome: "Serviços em Alimentação")
Categoria.create( nome: "Serviços em Arte")
Categoria.create( nome: "Serviços em Cine / Foto / Som")
Categoria.create( nome: "Serviços em Comunicação")
Categoria.create( nome: "Serviços em Construção")
Categoria.create( nome: "Serviços em Ecologia / Meio Ambiente")
Categoria.create( nome: "Serviços em Eletroeletrônica / Metal Mecânica")
Categoria.create( nome: "Serviços em Festas / Eventos")
Categoria.create( nome: "Serviços em Informática")
Categoria.create( nome: "Serviços em Internet")
Categoria.create( nome: "Serviços em Jóias / Relógios / Óticas")
Categoria.create( nome: "Serviços em Telefonia")
Categoria.create( nome: "Serviços em Veículos")
Categoria.create( nome: "Serviços Esotéricos / Místicos")
Categoria.create( nome: "Serviços Financeiros")
Categoria.create( nome: "Serviços Funerários")
Categoria.create( nome: "Serviços Gerais")
Categoria.create( nome: "Serviços Gráficos / Editoriais")
Categoria.create( nome: "Serviços para Animais")
Categoria.create( nome: "Serviços para Deficientes")
Categoria.create( nome: "Serviços para Escritórios")
Categoria.create( nome: "Serviços para Roupas")
Categoria.create( nome: "Serviços Socias / Assistenciais")
Categoria.create( nome: "Sex Shop")
Categoria.create( nome: "Shopping Centers")
Categoria.create( nome: "Tabacaria")
Categoria.create( nome: "Tarifas Bancárias")
Categoria.create( nome: "Tarifas Telefônicas")
Categoria.create( nome: "Telefonia")
Categoria.create( nome: "Turismo")


